package br.com.fsilveira.finance.entity;

// Generated 17/08/2012 23:01:50 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "banco", uniqueConstraints = @UniqueConstraint(columnNames = { "codigo", "nome", "instancia" }))
public class Banco extends AbstractBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "seq_banco", sequenceName = "seq_banco")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_banco")
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instancia")
	private Instancia instancia;

	@Column(name = "ativo")
	private Boolean ativo;

	@Column(name = "codigo")
	private String codigo;

	@Column(name = "nome")
	private String nome;

	@Column(name = "site")
	private String site;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	private List<ContaBancaria> contaBancarias;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Instancia getInstancia() {
		return instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public Boolean getAtivo() {
		return ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getSite() {
		return site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	public List<ContaBancaria> getContaBancarias() {
		return contaBancarias;
	}

	public void setContaBancarias(List<ContaBancaria> contaBancarias) {
		this.contaBancarias = contaBancarias;
	}

}
