package br.com.fsilveira.finance.entity;

// Generated 17/08/2012 23:01:50 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ContaBancaria generated by hbm2java
 */
@Entity
@Table(name = "conta_bancaria")
public class ContaBancaria extends AbstractBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "seq_conta_bancaria", sequenceName = "seq_conta_bancaria")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_conta_bancaria")
	private Long id;

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Conta conta;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banco")
	private Banco banco;

	@Column(name = "agencia")
	private Long agencia;

	@Column(name = "tipo_conta", nullable = false)
	private int tipoConta;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaBancaria")
	private List<ContaCartaoCredito> contaCartaoCreditos;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public Banco getBanco() {
		return banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public Long getAgencia() {
		return agencia;
	}

	public void setAgencia(Long agencia) {
		this.agencia = agencia;
	}

	public int getTipoConta() {
		return tipoConta;
	}

	public void setTipoConta(int tipoConta) {
		this.tipoConta = tipoConta;
	}

	public List<ContaCartaoCredito> getContaCartaoCreditos() {
		return contaCartaoCreditos;
	}

	public void setContaCartaoCreditos(List<ContaCartaoCredito> contaCartaoCreditos) {
		this.contaCartaoCreditos = contaCartaoCreditos;
	}

}
