package br.com.fsilveira.finance.entity;

// Generated 17/08/2012 23:01:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Feriado generated by hbm2java
 */
@Entity
@Table(name = "feriado", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Feriado extends AbstractBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = -341701858076670103L;
	@Id
	@SequenceGenerator(name = "seq_feriado", sequenceName = "seq_feriado")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_feriado")
	private Long id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instancia")
	private Instancia instancia;
	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 13)
	private Date data;
	private String descricao;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Instancia getInstancia() {
		return instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public Date getData() {
		return data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
