package br.com.fsilveira.finance.entity;

// Generated 17/08/2012 23:01:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Instancia generated by hbm2java
 */
@Entity
@Table(name = "instancia", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Instancia extends AbstractBean {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@SequenceGenerator(name = "seq_instancia", sequenceName = "seq_instancia")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_instancia")
	private Long id;
	@Column(name = "fundo_caixa", nullable = false, precision = 18)
	private BigDecimal fundoCaixa;
	@Column(name = "nome", unique = true, nullable = false, length = 40)
	private String nome;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Conta> contas = new HashSet<Conta>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<CedenteSacado> cedenteSacados = new HashSet<CedenteSacado>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Feriado> feriados = new HashSet<Feriado>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Categoria> categorias = new HashSet<Categoria>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Lancamento> lancamentos = new HashSet<Lancamento>(0);
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instancia")
	private Set<Banco> bancos = new HashSet<Banco>(0);
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public BigDecimal getFundoCaixa() {
		return fundoCaixa;
	}
	public void setFundoCaixa(BigDecimal fundoCaixa) {
		this.fundoCaixa = fundoCaixa;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public Set<Conta> getContas() {
		return contas;
	}
	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}
	public Set<CedenteSacado> getCedenteSacados() {
		return cedenteSacados;
	}
	public void setCedenteSacados(Set<CedenteSacado> cedenteSacados) {
		this.cedenteSacados = cedenteSacados;
	}
	public Set<Usuario> getUsuarios() {
		return usuarios;
	}
	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
	public Set<Feriado> getFeriados() {
		return feriados;
	}
	public void setFeriados(Set<Feriado> feriados) {
		this.feriados = feriados;
	}
	public Set<Categoria> getCategorias() {
		return categorias;
	}
	public void setCategorias(Set<Categoria> categorias) {
		this.categorias = categorias;
	}
	public Set<Lancamento> getLancamentos() {
		return lancamentos;
	}
	public void setLancamentos(Set<Lancamento> lancamentos) {
		this.lancamentos = lancamentos;
	}
	public Set<Banco> getBancos() {
		return bancos;
	}
	public void setBancos(Set<Banco> bancos) {
		this.bancos = bancos;
	}

}
