package br.com.fsilveira.finance.entity;

// Generated 17/08/2012 23:01:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.joda.time.LocalDateTime;

/**
 * Lancamento generated by hbm2java
 */
@Entity
@Table(name = "lancamento")
public class Lancamento extends AbstractEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@SequenceGenerator(name = "seq_lancamento", sequenceName = "seq_lancamento")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_lancamento")
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedente_sacado")
	private CedenteSacado cedenteSacado;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoria")
	private Categoria categoria;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instancia")
	private Instancia instancia;

	@Column(name = "descricao", length = 60)
	private String descricao;

	@Column(name = "historico")
	private String historico;

	@Column(name = "tipo_lancamento")
	private Tipo tipo;

	@Column(name = "repeticao_indefinida")
	private Boolean repeticaoIndefinida;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lancamento")
	private List<ParcelaLancamento> parcelaLancamentos = new ArrayList<ParcelaLancamento>(0);

	private transient Conta conta;
	private transient LocalDateTime dataPgto;
	private transient LocalDateTime dataVencimento;
	private transient Integer parcela;
	private transient BigDecimal valor;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public CedenteSacado getCedenteSacado() {
		return cedenteSacado;
	}

	public void setCedenteSacado(CedenteSacado cedenteSacado) {
		this.cedenteSacado = cedenteSacado;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Instancia getInstancia() {
		return instancia;
	}

	public void setInstancia(Instancia instancia) {
		this.instancia = instancia;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getHistorico() {
		return historico;
	}

	public void setHistorico(String historico) {
		this.historico = historico;
	}

	public Boolean getRepeticaoIndefinida() {
		return repeticaoIndefinida;
	}

	public void setRepeticaoIndefinida(Boolean repeticaoIndefinida) {
		this.repeticaoIndefinida = repeticaoIndefinida;
	}

	public List<ParcelaLancamento> getParcelaLancamentos() {
		return parcelaLancamentos;
	}

	public void setParcelaLancamentos(List<ParcelaLancamento> parcelaLancamentos) {
		this.parcelaLancamentos = parcelaLancamentos;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public LocalDateTime getDataPgto() {
		return dataPgto;
	}

	public void setDataPgto(LocalDateTime dataPgto) {
		this.dataPgto = dataPgto;
	}

	public LocalDateTime getDataVencimento() {
		return dataVencimento;
	}

	public void setDataVencimento(LocalDateTime dataVencimento) {
		this.dataVencimento = dataVencimento;
	}

	public Integer getParcela() {
		return parcela;
	}

	public void setParcela(Integer parcela) {
		this.parcela = parcela;
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public enum Tipo {
		DESPESA, RECEITA
	}

	public Tipo getTipo() {
		return tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

}
